#!/bin/sh
set -eu

for variable in \
  POSTGRES_DB VENTA_MIGRATOR_PASSWORD VENTA_APP_PASSWORD VENTA_AUTH_PASSWORD \
  VENTA_INGRESS_PASSWORD VENTA_BACKUP_PASSWORD VENTA_RESTORE_PASSWORD
do
  eval "value=\${$variable:-}"
  [ -n "$value" ] || { echo "ERROR: $variable es obligatorio para initdb" >&2; exit 1; }
done

psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" --set ON_ERROR_STOP=1 \
  --set database_name="$POSTGRES_DB" \
  --set migrator_password="$VENTA_MIGRATOR_PASSWORD" \
  --set app_password="$VENTA_APP_PASSWORD" \
  --set auth_password="$VENTA_AUTH_PASSWORD" \
  --set ingress_password="$VENTA_INGRESS_PASSWORD" \
  --set backup_password="$VENTA_BACKUP_PASSWORD" \
  --set restore_password="$VENTA_RESTORE_PASSWORD" <<'SQL'
CREATE ROLE venta_owner NOLOGIN NOINHERIT;
CREATE ROLE venta_migrator LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD :'migrator_password' CONNECTION LIMIT 4;
CREATE ROLE venta_app LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD :'app_password' CONNECTION LIMIT 30;
CREATE ROLE venta_auth LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD :'auth_password' CONNECTION LIMIT 10;
CREATE ROLE venta_ingress LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD :'ingress_password' CONNECTION LIMIT 10;
CREATE ROLE venta_backup LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION BYPASSRLS PASSWORD :'backup_password' CONNECTION LIMIT 2;
CREATE ROLE venta_restore LOGIN NOINHERIT NOSUPERUSER CREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS PASSWORD :'restore_password' CONNECTION LIMIT 2;
GRANT venta_owner TO venta_migrator WITH INHERIT FALSE, SET TRUE;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE CONNECT ON DATABASE :"database_name" FROM PUBLIC;
GRANT CONNECT ON DATABASE :"database_name" TO venta_migrator, venta_app, venta_auth, venta_ingress, venta_backup;
REVOKE CONNECT ON DATABASE :"database_name" FROM venta_restore;
CREATE EXTENSION IF NOT EXISTS vector;
ALTER DATABASE :"database_name" OWNER TO venta_owner;
ALTER SCHEMA public OWNER TO venta_owner;
SQL
